image: node:20-alpine

stages:
  - build

pages:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
